apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.13.2
  nodeSets:
  - name: default
    podTemplate:
      metadata:
      spec:
        containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 12Gi
                cpu: 1
              limits:
                memory: 12Gi
                cpu: 4
    count: 3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
        storageClassName: nfs-storageclass
    config:
      node.store.allow_mmap: false